### ISSUE TITLE
Unknown column 'resource.resource_id' in sparql/index_triplestore/job

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-Sparql#3]
I installed release Sparql-3.4.2 (and also Common-3.4.48), started the index process and got:

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'resource.resource_id' in 'on clause' in /home/http/goudatijdmachine.nl/omeka-s-4.0.4/vendor/doctrine/dbal/lib                                              /Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79
Stack trace:
#0 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertExcep                                              tion()
#1 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException()
#2 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2222): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(                                              )
#3 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1312): Doctrine\DBAL\Connection->handleExceptionDuringQuery()
#4 /home/http/goudatijdmachine.nl/omeka-s-modules/Sparql/src/Job/IndexTriplestore.php(486): Doctrine\DBAL\Connection->executeQuery()
#5 /home/http/goudatijdmachine.nl/omeka-s-modules/Sparql/src/Job/IndexTriplestore.php(341): Sparql\Job\IndexTriplestore->initPrefixesUsed()
#6 /home/http/goudatijdmachine.nl/omeka-s-modules/Sparql/src/Job/IndexTriplestore.php(246): Sparql\Job\IndexTriplestore->initOptions()
#7 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/application/src/Job/DispatchStrategy/Synchronous.php(34): Sparql\Job\IndexTriplestore->perform()
#8 /home/http/goudatijdmachine.nl/omeka-s-modules/Log/src/Job/Dispatcher.php(78): Omeka\Job\DispatchStrategy\Synchronous->send()
#9 /home/http/goudatijdmachine.nl/omeka-s-4.0.4/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send()
#10 {main} {"userId":2,"jobId":1757,"referenceId":"sparql/index_triplestore/job_1757"}

**Comment by coret** [comment]
Should this be `resource.id` or `resource.resource_class_id`?

**Comment by coret** [comment]
https://github.com/Daniel-KM/Omeka-S-module-Sparql/blob/c82c40533d5189104a854927471d1750368ffda1/src/Job/IndexTriplestore.php#L479

`resource.resource_id` does not exist

Work-around: do not index media
